name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Setup database
      run: |
        sudo apt-get install -y postgresql-client
        psql -h localhost -U postgres -c "CREATE DATABASE mydb;"
      env:
        PGPASSWORD: password

    - name: Run database migrations
      run: bundle exec rake db:migrate

    - name: Run tests
      run: bundle exec rake test
