name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Ensure all bin files are executable
      run: chmod +x bin/*

    - name: Setup database for SQLite
      run: |
        # Создание директории и файла SQLite базы данных
        mkdir -p db
        touch db/test.sqlite3

    - name: Check and migrate database
      run: |
        # Проверка и выполнение миграций базы данных SQLite
        bundle exec rails db:migrate RAILS_ENV=test

    - name: Run tests
      run: |
        # Запуск тестовf Ruby on Rails
        bundle exec rails test RAILS_ENV=test
